# site settings

title: Anish Devineni
description: Welcome to my wesbite!
taglong: Welcome to my wesbite!
tagshort: Jekyll theme
url: https://anishd.com
baseurl: ""
permalink: pretty
repo: https://github.com/anishcd/anishcd.github.io

# author settings

author:
  name: Anish Devineni
  email: anishcdevineni@gmail.com
photo: /assets/profile_main.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
